package main

var moduleTypes = map[string]string{
	"Ai": "ModuleTypeAirlock",
	"An": "ModuleTypeAntiMeteorLaser",
	"Ba": "ModuleTypeBar",
	"Bs": "ModuleTypeBasePad",
	"Bi": "ModuleTypeBioDome",
	"Ca": "ModuleTypeCabin",
	"Cn": "ModuleTypeCanteen",
	"Co": "ModuleTypeControlCenter",
	"Do": "ModuleTypeDorm",
	"Fa": "ModuleTypeFactory",
	"La": "ModuleTypeLab",
	"Ln": "ModuleTypeLandingPad",
	"Li": "ModuleTypeLightningRod",
	"Mi": "ModuleTypeMine",
	"Mo": "ModuleTypeMonolith",
	"Mu": "ModuleTypeMultiDome",
	"Ox": "ModuleTypeOxygenGenerator",
	"Po": "ModuleTypePowerCollector",
	"Pr": "ModuleTypeProcessingPlant",
	"Py": "ModuleTypePyramid",
	"Ra": "ModuleTypeRadioAntenna",
	"Ro": "ModuleTypeRoboticsFacility",
	"Si": "ModuleTypeSickBay",
	"Sg": "ModuleTypeSignpost",
	"So": "ModuleTypeSolarPanel",
	"St": "ModuleTypeStarport",
	"Sr": "ModuleTypeStorage",
	"Te": "ModuleTypeTelescope",
	"Wa": "ModuleTypeWaterExtractor",
	"Wt": "ModuleTypeWaterTank",
	"Wi": "ModuleTypeWindTurbine",
}

var moduleSizes = map[string]int64{
	"Ai": 0,
	"An": 1,
	"Ba": 2,
	"Bs": 0,
	"Bi": 4,
	"Ca": 1,
	"Cn": 2,
	"Co": 2,
	"Do": 2,
	"Fa": 2,
	"La": 1,
	"Ln": 2,
	"Li": 1,
	"Mi": 1,
	"Mo": 2,
	"Mu": 2,
	"Ox": 1,
	"Po": 3,
	"Pr": 2,
	"Py": 4,
	"Ra": 2,
	"Ro": 2,
	"Si": 1,
	"Sg": 1,
	"So": 4,
	"St": 4,
	"Sr": 4,
	"Te": 2,
	"Wa": 2,
	"Wt": 2,
	"Wi": 3,
}

var sizeToFloat = map[int64]float64{
	4: 8.75,
	3: 7.75,
	2: 6.25,
	1: 4.75,
	0: 3.75,
}
